name: Build Streamlink Linux

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[decompress] pyinstaller
          pip install --upgrade .[decompress]

      - name: Hardcode version in _version.py
        run: |
          echo '__version__ = "7.6.0"' > src/streamlink/_version.py
          cat src/streamlink/_version.py

      - name: Create PyInstaller entry script
        run: |
          mkdir -p build
          echo 'from streamlink_cli.main import main; main()' > build/entry_point.py
          cat build/entry_point.py

      - name: Run PyInstaller to produce single-file EXE
        run: |
          pyinstaller --noconfirm --onefile \
            --name streamlink \
            --add-data "src/streamlink/_plugins.json:streamlink" \
            build/entry_point.py

      - name: Show dist folder
        run: ls -la dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: streamlink-linux-${{ matrix.os }}
          path: dist/streamlink
