name: Build Streamlink for Multiple Platforms

on:
  workflow_dispatch:  # 添加手动触发事件

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            name: linux
            binary-name: streamlink
          - os: windows-latest
            name: windows
            binary-name: streamlink.exe

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Build Binary with PyInstaller
        run: |
          pyinstaller --onefile --name ${{ matrix.binary-name }} src/streamlink_cli/main.py
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: streamlink-${{ matrix.name }}
          path: dist/${{ matrix.binary-name }}

  build-appimage:
    name: Build Linux AppImage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Build Binary with PyInstaller
        run: |
          pyinstaller --onefile --name streamlink src/streamlink_cli/main.py
      - name: Install appimagetool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
      - name: Create AppImage
        run: |
          mkdir -p AppDir/usr/bin
          cp dist/streamlink AppDir/usr/bin/
          mkdir -p AppDir/usr/share/applications
          echo "[Desktop Entry]
          Name=Streamlink
          Exec=streamlink
          Type=Application
          Terminal=true" > AppDir/usr/share/applications/streamlink.desktop
          ln -s usr/bin/streamlink AppDir/AppRun
          ./appimagetool-x86_64.AppImage AppDir streamlink-x86_64.AppImage
      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: streamlink-appimage
          path: streamlink-x86_64.AppImage
