name: Build Streamlink for Multiple Platforms

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        include:
          #- os: ubuntu-22.04
          #  name: linux
          #  binary-name: streamlink
          - os: windows-latest
            name: windows
            binary-name: streamlink.exe

    steps:
      # 检出代码
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # 提取依赖到requirements.txt，避免pip install .触发versioningit
          pip install toml
          python -c "import toml; config = toml.load('pyproject.toml'); deps = config['project']['dependencies']; print('\n'.join(deps))" > requirements.txt
          pip install -r requirements.txt
          pip install -r dev-requirements.txt


      # 构建二进制
      - name: Build Binary with PyInstaller
        run: |
          pyinstaller --onefile --name ${{ matrix.binary-name }} src/streamlink_cli/main.py

      # 上传二进制Artifacts
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: streamlink-${{ matrix.name }}
          path: dist/${{ matrix.binary-name }}

  
